### ISSUE TITLE
Creating the Pre-user input form

### ISSUE THREAD

**Issue by jbubar** [hackforla/new-schools-today#12]
### Overview
Create a survey to understand user needs in the student, staff, and parent categories.

### Action Items
Make the survey
Include feature ideas
Include different user groups
keep it short

Research other early user feedback surveys and compare

### Resources/Instructions
 [scrum article](https://medium.com/the-liberators/7-powerful-ways-to-get-feedback-from-users-in-scrum-b683d39143ca)

[working draft](https://docs.google.com/forms/d/e/1FAIpQLSf5SQIbgmg69Pf0xtx_CBMgYVJ-lJTqTJcOQErySHlKh4AAvg/viewform?usp=sf_link)

**Comment by jbubar** [comment]
@Rankazze could you take a look at this issue and contribute some scrum knowledge?

**Comment by jbubar** [comment]
@jasonTelanoff Are you ready for this to go live? What is the next step on this?

**Comment by jasonTelanoff** [comment]
The form made is now outdated. It has been completed, however.

**Comment by theswerd** [comment]
It looks like we will be doing user research from the bottom up, in a sprint style, so a standardized user input form isn't currently necessary

**Comment by jbubar** [comment]
great Ill close it
