### ISSUE TITLE
Thank you notes to our React tutors!

### ISSUE THREAD

**Issue by jbubar** [hackforla/new-schools-today#15]
### Overview
Write a thank you note to the developers who have taken their time to tutor us about React.js

### Action Items

- [x] Write a draft
- [x] share and revise the draft
- [x] have everyone sign the card
- [ ] deliver or mail the card
- [ ] create a spreadsheet of people to thank

**Comment by jbubar** [comment]
@theswerd Did we send Michelle B. a card?

**Comment by JacobZwang** [comment]
create spreadsheet @jbubar 
please link spreadsheet in this issue

**Comment by jbubar** [comment]
https://docs.google.com/spreadsheets/d/1rEjL5bWhznoPlnFXm0LEC8pJZo8w0twy1ahsuyjYo-Q/edit?usp=sharing

**Comment by jbubar** [comment]
added Yihana ritter who helped with our ucla presentation to our contributor list
