### ISSUE TITLE
Project Problem Statement

### ISSUE THREAD

**Issue by theswerd** [hackforla/new-schools-today#18]
### Overview
Our team needs a clear and concise statement of our end goal and how we plan to reach it

### Action Items
- Make the project card 
- Make the project page 
- Make the mission statement
- Write plan @Rankazze 

Ps. @jbubar does this issue look ok?

**Comment by jbubar** [comment]
@theswerd this is great, but I think we are going to split this into smaller issues.
Message me if you have a different plan
