### ISSUE TITLE
Website: Update project profile for new-schools-today

### ISSUE THREAD

**Issue by jbubar** [hackforla/new-schools-today#24]
### Overview
 Update the following fields for our project. These updated fields will then be updated to be shown on the website.

***taken from [Harish's github issue](https://github.com/hackforla/website/issues/249)

### Action Items

- [x] - Update wording of anything currently on the project card (see hackforla.org)
- [ ] -  Update "Tools" Section to display the tools being used for the project (Ex: figma, Balsamiq, photoshop, etc.)
- [ ] -  Update "Looking For" Section
- [ ] -  Update any links that are not currently displayed on the site (do you have a demo site?)
- [ ] -  Banner Image to be displayed on project specific page 16:9 ratio (min width 1200px)
- [ ] -  Any resources for a Getting Started link (either a link to a wiki or readme)

### Resources/Instructions
Rough example of a good banner image from the helloGOV project:

![](https://user-images.githubusercontent.com/37763229/71553521-b75f6580-29c5-11ea-892e-0f0391069dc7.png)

**Comment by jbubar** [comment]
Nicole, Would you like to work with me on splitting this into multiple issues?

**Comment by ExperimentsInHonesty** [comment]
This issue is duplicative, with #257, because team did not already have a website card.  I am closing the issue.
