### ISSUE TITLE
Start Coding Option #1 -- Platform Website

### ISSUE THREAD

**Issue by theswerd** [hackforla/new-schools-today#25]
This issue is for project managers @jbubar and @nicolekelner 

Start coding the front end of the website.
The main options for this are Vue or React.
React is used in 2,958,748 public projects on GitHub, while Vue is only used in 1,199,437.

I believe we should start with React, as Jason and I are already studying it and using it on other projects. There are also more React developers at HFLA then Vue developers.

If you approve I will open a new React project and set it up with Material UI and Material UI Design Icons, so we can start engineering the front end of the website that people will use to design the apps.

If you think we should use Vue instead we will need  Nicole to create it, as I have no experience with Vue.

Finally, I am putting this issue in the Icebox as we can't start on it until @jbubar approves. Once a decision is made please move it to the "In progress" section.

**Comment by jbubar** [comment]
@theswerd @nicolekelner  @Rankazze I’m on board with the spirit of this! I think react makes more sense. I’d love to here what Nicole thinks. 

I acknowledge that I sorta gave you the ok to start building, but I am not 100% sure that building the front end of the website is the first thing to get done, and I would like to meet w the product owner before I give a definitive yes. 

It appears that our first big goals are finding a sponsor and creating an inspiring talk for the upcoming UCLA conference. Are we looking to create a minimum viable project to meet those goals? 

Thinking out loud here. 
I’m going to send Some messages and get back to you in 48 hours. In the mean time I’d love to hear your thoughts.

**Comment by theswerd** [comment]
Since we have started building the website in ReactJS this issue is outdated
