### ISSUE TITLE
Staff Directory Base

### ISSUE THREAD

**Issue by jasonTelanoff** [hackforla/new-schools-today#27]
### Overview
Add a staff directory that will display json data in a clear fashion.

### Action Items
- Create  **staffdirectory.dart**
- Create a class for a staff member
- Create a widget for each staff member
- Create a scaffold with a listview.seperated for each staff member

### Dependencies

@Henrymarks1 is working on a JSON parser, this will use that parser.
#31 
### Resources/Instructions
- Make sure it is created within a **staffdirectory.dart** file
- No hardcoded colors

**Comment by JacobZwang** [comment]
@Henrymarks1 Please update this issue
1. Progress 
2. Blocks 
3. availability
4. ETA
