### ISSUE TITLE
React Router

### ISSUE THREAD

**Issue by theswerd** [hackforla/new-schools-today#28]
### Overview
Our platform website is just getting started, and we need to set up a router on it.

### Action Items

- Create website link hierarchy 
- Decide our component architecture

### Resources/Instructions
We are looking for help on this. If you are interested please let me know on this PR.

**Comment by ExperimentsInHonesty** [comment]
@theswerd are you working on this.  You self assigned but it's in the prioritized backlog, not the in progress.

**Comment by theswerd** [comment]
Finished at #bd6cbb4
