### ISSUE TITLE
App architecture

### ISSUE THREAD

**Issue by theswerd** [hackforla/new-schools-today#29]
### Overview
We need a clear architecture that is easy to understand, contribute to, easy to use for the app.

### Action Items

- Create proposal to Standardize how new functions/pages are added -- Please put in comments here

### Resources/Instructions
[Medium Article #1](https://medium.com/flutter-community/flutter-navigation-cheatsheet-a-guide-to-named-routing-dc642702b98c)
[Medium Article #2](https://medium.com/flutter-community/flutter-routes-and-navigation-69f128a9ea8f)

**Comment by ExperimentsInHonesty** [comment]
@jasonTelanoff update is
1. Progress - none
2. Blocks - Availability
3. Availability is more time next week 2/2 -8/20.
4. ETA - unknown until 8th.

will try to figure out what kind of advice is needed for Monday recruitment.

**Comment by jasonTelanoff** [comment]
Branch has been merged
