### ISSUE TITLE
Flutter Router/Homepage code

### ISSUE THREAD

**Issue by theswerd** [hackforla/new-schools-today#31]
### Overview
Create central router and homepage code

### Action Items
- Standardize navigation practices -- Central Navigator/Router for pages in main.dart file
- Create central app homepage with that allows users to navigate to any app function

- When completed please move #27 from Icebox to prioritized backlog, and annotate it with the status of this plugin

### Resources/Instructions
- Make sure that the homepage file is not in main.dart, and that it has its own file

**Comment by jasonTelanoff** [comment]
### Resources/Instructions
[Medium Article #1](https://medium.com/flutter-community/flutter-navigation-cheatsheet-a-guide-to-named-routing-dc642702b98c)
[Medium Article #2](https://medium.com/flutter-community/flutter-routes-and-navigation-69f128a9ea8f)

**Comment by jasonTelanoff** [comment]
### Update to Resources/Instructions
[Medium Article #1](https://medium.com/flutter-community/flutter-navigation-cheatsheet-a-guide-to-named-routing-dc642702b98c)
[Medium Article #2](https://medium.com/flutter-community/flutter-routes-and-navigation-69f128a9ea8f)

**Comment by jasonTelanoff** [comment]
I started on the router. The main.dart file will display the correct page. To view the code, view the "routers" branch

**Comment by jasonTelanoff** [comment]
Pages can now navigate to other pages. I need to handle undefined routers, pass parameters, and some other stuff.

**Comment by jasonTelanoff** [comment]
I did all of that Wednesday, forgot to check in. I just need to figure out how to pass several parameters of different types

**Comment by jasonTelanoff** [comment]
I finished making a simple router. It works, and looks clean. @theswerd and I should talk more about the router's complexity and efficiency. As for the homepage, I think that should be a different issue
