### ISSUE TITLE
UCLA 

### ISSUE THREAD

**Issue by jbubar** [hackforla/new-schools-today#33]
### Overview
Preparing the presentation for our talk at UCLA

### Action Items
- [x] get clear what the requirements are for the talk (time limit, size of room, use of technology, etc.)
- [x] Create an outline for the talk and get Bonnie's approval
- [x] create a slide deck
- [x] practice the talk and get feedback
- [x] submit our talk to the organizers

### Resources/Instructions

[Google Slides Presentation](https://docs.google.com/presentation/d/1oH5pEYG2kBCK-v4-nYLpdnUQgV3o7FIkdOZtiwk7bKI/edit?usp=sharing)

REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

[Bonnie's project narrative](https://docs.google.com/document/d/1SB1xpyWjfEQTkip4_Nu_H02yfhzh2SUTdmFEip2Fzus/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
This is what Nicole sent


Nicole Kelner  1/13/20 8:54 PM
Here's the title + description
Empathy through Apps: Reimagining new student onboarding
We will discuss human-centered design principles in relation to building technology. Learn about the development process of an app for new students, envisioned by students, to feel welcome as soon as they walk into school.

**Comment by ExperimentsInHonesty** [comment]
Proposal for talk sent to Vanessa on 2/7
**Title** 
Empathy through applications: How a student led team team is using technology to connect students with their new peers.

**Elevator Pitch**
Imagine on the first day of school, if there was an app, that could guide you to every class, remind you when a club meeting you want to check out is happening, help you find your locker, and so much more.  Our student-lead team is building the open source platform for every school to have this.

**Description**
Meet the first ever high school lead team in the Code for America (CfA) network.   With the help of Hack for LA (LA’s local CfA brigade), we have been able to create a team complete with beginners, experts, coders, designers, and documentarians.  In this talk we will cover who we are, what we do, and how anyone, even with no experience, can get involved. You will learn about the team structure: mobile app development, website development, and product management. We will give share details about the tools, technologies and techniques we are using in each of them, why we chose them, and how you can join us.

**Notes**
We will need a projector, and ideally a microphone or two for audience member questions. This talk is meant to inspire high school students to get involved in their local communities.  We have material to cover the whole time, but plan on holding back ½ of it to allow time for audience questions.

**Comment by Araceli2004** [comment]
https://docs.google.com/document/d/1SB1xpyWjfEQTkip4_Nu_H02yfhzh2SUTdmFEip2Fzus/edit

**Comment by Araceli2004** [comment]
This is a document that hopefully gives more information about the presentation

**Comment by Araceli2004** [comment]
https://docs.google.com/presentation/d/1oH5pEYG2kBCK-v4-nYLpdnUQgV3o7FIkdOZtiwk7bKI/edit#slide=id.g7d4d3b2d1c_1_5

**Comment by JacobZwang** [comment]
Bonnie will wright to her on Monday.

**Comment by JacobZwang** [comment]
I just spent around 8 hours restructuring and rethinking the slides. There is still a fair amount of polish to be done: refining sentences, replacing images, etc. It is visually broken up into 2 parts, the dark beginning section representing our lack of real progress and the light section, representing out triumphs and what we learned from our failures. Hopefully, this gives the writers an idea of where to head. Let me know what you guys think.

**Comment by Araceli2004** [comment]
https://docs.google.com/presentation/d/1tXcUf3-wAxrGThp93GFCXvbFHHOiLFicpDqiuFNhMbo/edit#slide=id.g7e532e8752_0_32
Edit: 2/17/20

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2020-03-01 at 1 49 47 PM](https://user-images.githubusercontent.com/37763229/75634545-d647c700-5bc3-11ea-9e44-e9399149b636.png)

**Comment by ethanh256** [comment]
UCLA Retrospective: 

9 members from our team: @theswerd @jasonTelanoff @jbubar @JacobZwang @Araceli2004 @ethanh256 @ExperimentsInHonesty @Pinkuremonedo @Henrymarks1 

We had 26 attendees at our presentation, plus more people who heard about us from tabling, 6 girls total. 

Design workshop: @JacobZwang says,
- around 75% of participants engagement
- could've used more structure, computers
- 14 participants

Intro to Programming workshop: @ethanh256 and @Henrymarks1 say: 
- 8 participants
- mostly (75%) engaged
- good, appropriate content

(Advanced) Mobile App Development workshop:
- 100% engagement
- should've been easier, should've held hands more
- 4 participants

Suggestions for next time: 
- take attendance/roll for everyone
- hosts expected earlier start time, most schools came later
- no more than 10 team members <-- ambassador attendance maximum
- prepare the room earlier, set up everything

Great job guys! Overall, the general census is that it went very well.
