### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by theswerd** [hackforla/new-schools-today#34]
### Overview
New Schools Today Meeting Itinerary
January 31, 2019
### Action Items

Meeting starts at 6:30

- 10 minute intro
- Progress
     - Review in-progress
          - Progress
          - Blocks
          - Availability
          - ETA
     - ReactJS website with material UI
     - Flutter App getting started
- Jobs Today
     - UCLA PRESENTATION DUE TONIGHT
     - Design Favicon logo
     - Get update on HFLA Website progress
     - Continue app configuration
     - Onboarding
          - Looking for ReactJS/Material UI for web
          - Travis/CircleCI/AWS for pull request management and automated tasks
          - Flutter developer
- Ending
     - Final 10 minutes go over progress
     - Assign homework
     - Lecture from Dean/Josh?

Goals:
Working website and app ready for contributors

**Comment by JacobZwang** [comment]
### Overview
New Schools Today Meeting Itinerary
Feb 17, 2020
### Action Items

Meeting starts at 6:30

- 10 minute intro
- Progress
     - Review in-progress
          - Progress
          - Blocks
          - Availability
          - ETA
- Jobs Today
          -Discuss Staff Directory Design #41 
- Ending
     - Final 10 minutes go over progress
     - Assign homework
     - Lecture from Dean/Josh?

Goals:
