### ISSUE TITLE
Find a react.js tutor

### ISSUE THREAD

**Issue by jbubar** [hackforla/new-schools-today#7]
### Overview
Look for a react.js developer to volunteer their time to tutor our developer team. 

### Action Items

- [ ] Draft a message to HfLA #general slack channel
- [ ] Share with Bonnie for review
- [x] Post message to HfLA #general slack channel
- [x] Check in with Bonnie about potential react tutor named Joel

**Comment by theswerd** [comment]
@jbubar can you give me a description of what the tutors responsibilities will be?

**Comment by ExperimentsInHonesty** [comment]
Revised plan
Bonnie reached out to her network asking for appropriate tutors and has scheduled the following:

- [x] 1st tutor from Boston 12/9
- [ ] 2d tutor from DTLA 12/16 

@theswerd @jbubar please draft thank you notes that I can mail to our first tutor.  She will really appreciate it.

**Comment by ExperimentsInHonesty** [comment]
@theswerd @jbubar or just draft one thank you note, signed by the whole team next week for her, and another for Joel.

**Comment by ExperimentsInHonesty** [comment]
Also, is this an ongoing need?  Please let me know.

**Comment by jbubar** [comment]
Hi Ben,
I am not sure what the tutors responsibilities would be. Bonnie? Would you
know?

And I really like idea to draft a thank you letter. Here is a quick
starting draft.

“Thank you for training our team! We had such a good time learning from
you. Our team is committed to creating quality websites and exposing our
young developers to civic hacking. We are so grateful for the positive
learning experience that you provided for us.

With gratitude,

new-schools-today team. “

Lastly,
I really like the idea of having this react tutoring be a consistent thing
for now. I think it creates an environment where students feel legitimized
and productive.

All the best,
Josh

**Comment by theswerd** [comment]
This issue is outdated. We have gotten sufficient tutoring and have already began programming. If the opportunity of a tutor presents itself I don't think we would be opposed, however the purpose of this issue was to sufficiently educate our development team, which I believe we have done.
