### ISSUE TITLE
Agenda 2020-04-06

### ISSUE THREAD

**Issue by ghost** [hackforla/new-schools-today#79]
### Overview
Gather all items team members want to propose for this weeks' agenda.

### Action Items
- Discuss website readme for new coders: issue #70 
- Add availability: issue #60 
- BEN'S OVERVIEW [LinkedIn suggestions by Bonnie](https://hackforla.slack.com/archives/CQZ5R91C5/p1585612484007600) (Ex: Hack for LA as "experience" rather than "volunteering")
- Go over the in-progress of project boards and update projects/recommit to getting the work done
- receive feedback from team: issue #41
- Discuss Figma usage for design team
- generate feature list based on TEAM OPINIONS and then eventually STUDENT OPINIONS
- Discuss Michael's workshop: overview & our availabilities

Add comment to this issue with your proposed agenda item. if item warrants an issue of its own please start a new issue, by going to the issues tab above and clicking on the New Issues green button.

**Comment by theswerd** [comment]
Plan to meet with Michael two Mondays from now if he is available.

**Comment by jbubar** [comment]
- Check in to see if @JacobZwang wants to stye the team wiki page and learn markdown style
- Build out ucla conference deliverable. i.e. add medium article and pictures
- Add all past agendas to the agenda section of the wiki
- consider hosting a call-athon or code-athon for NST where we can get the research for school districts done
